insert into speler (id, profielNaam, wachtwoord, winPercentage, correctPercentage) values (105515, 'Broozer', 'letter', 100, 100)
insert into speler (id, profielNaam, wachtwoord, winPercentage, correctPercentage) values (758341, 'Piepje', 'letter', 0, 50)
insert into vraag (id, vraag) values (1000, 'Eerste vraag: A, B, C of D?')
insert into antwoord (id, correct_jn, antwoord, vraagID) values (1001, 'N', 'A', 1000)
insert into antwoord (id, correct_jn, antwoord, vraagID) values (1002, 'J', 'B', 1000)
insert into antwoord (id, correct_jn, antwoord, vraagID) values (1003, 'N', 'C', 1000)
insert into antwoord (id, correct_jn, antwoord, vraagID) values (1004, 'N', 'D', 1000)
insert into vraag (id, vraag) values (1001, 'Tweede vraag: A, B, C of D?')
insert into antwoord (id, correct_jn, antwoord, vraagID) values (1005, 'J', 'A', 1001)
insert into antwoord (id, correct_jn, antwoord, vraagID) values (1006, 'N', 'B', 1001)
insert into antwoord (id, correct_jn, antwoord, vraagID) values (1007, 'N', 'C', 1001)
insert into antwoord (id, correct_jn, antwoord, vraagID) values (1008, 'N', 'D', 1001)
insert into highscores (id, spelerid, score) values (1, 105515, 1000)
insert into highscores (id, spelerid, score) values (2, 758341, 500)
